allowBuilds:
  esbuild: true
  workerd: true
patchedDependencies:
  '@embedpdf/plugin-annotation@2.15.1': patches/@embedpdf__plugin-annotation@2.15.1.patch
  '@embedpdf/plugin-selection@2.15.1': patches/@embedpdf__plugin-selection@2.15.1.patch
