import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Plugin } from 'vite';

const { version: appVersion } = JSON.parse(readFileSync(new URL('./package.json', import.meta.url), 'utf-8')) as {
  version: string;
};

// Dev only: saves PDFs generated by spikes to _spike-out/ (to inspect them without going through browser downloads)
function spikeSink() {
  return {
    name: 'spike-sink',
    apply: 'serve' as const,
    configureServer(server: { middlewares: { use(path: string, h: (req: any, res: any) => void): void } }) {
      const dir = join(process.cwd(), '_spike-out');
      mkdirSync(dir, { recursive: true });
      server.middlewares.use('/__spike/save', (req, res) => {
        const name = decodeURIComponent(
          new URL(req.url ?? '/', 'http://x').searchParams.get('name') ?? 'out.pdf',
        ).replace(/[^\w.-]/g, '_');
        const chunks: Buffer[] = [];
        req.on('data', (c: Buffer) => chunks.push(c));
        req.on('end', () => {
          writeFileSync(join(dir, name), Buffer.concat(chunks));
          res.end(JSON.stringify({ saved: name, bytes: Buffer.concat(chunks).length }));
        });
      });
    },
  };
}

// Chrome extension build (--mode extension): generates manifest.json and drops _headers, which is only for web hosting.
// background.ts is a separate rollup entry emitted under the fixed name background.js (referenced by the manifest)
function extensionFiles(): Plugin {
  let outDir = 'dist';
  return {
    name: 'extension-files',
    configResolved(config) {
      outDir = config.build.outDir;
    },
    generateBundle() {
      const manifest = JSON.parse(readFileSync('extension/manifest.json', 'utf-8')) as { version: string };
      manifest.version = appVersion;
      this.emitFile({ type: 'asset', fileName: 'manifest.json', source: JSON.stringify(manifest, null, 2) });
    },
    closeBundle() {
      rmSync(join(outDir, '_headers'), { force: true });
    },
  };
}

// Same CSP as production (keep in sync with public/_headers).
// The dev server relaxes only script-src, because Vite / React Refresh inject inline scripts.
const strictScriptSrc = "script-src 'self' 'wasm-unsafe-eval'";
const devScriptSrc = "script-src 'self' 'wasm-unsafe-eval' 'unsafe-inline'";
const csp = (scriptSrc: string) =>
  `default-src 'self'; ${scriptSrc}; style-src 'self' 'unsafe-inline'; img-src 'self' blob: data:; font-src 'self' data:; connect-src 'self'; worker-src 'self' blob:; object-src 'none'; frame-ancestors 'none'; base-uri 'self'; form-action 'none'`;

const isolationHeaders = {
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Cross-Origin-Embedder-Policy': 'require-corp',
};

export default defineConfig(({ mode }) => {
  const extension = mode === 'extension';
  return {
    define: { __APP_VERSION__: JSON.stringify(appVersion), __EXTENSION__: extension },
    build: extension
      ? {
          outDir: 'dist-ext',
          rollupOptions: {
            input: { main: 'index.html', background: 'extension/background.ts' },
            output: { entryFileNames: (c) => (c.name === 'background' ? 'background.js' : 'assets/[name]-[hash].js') },
          },
        }
      : undefined,
    plugins: [
      react(),
      spikeSink(),
      extension && extensionFiles(),
      // Offline support: precache the WASM, fonts and app.
      // Not depending on the network also shows that nothing is being sent.
      // The extension is already a local package, so it does not use a Service Worker
      !extension &&
        VitePWA({
          registerType: 'autoUpdate',
          // The CSP forbids inline scripts, so the registration script is loaded from a separate file
          injectRegister: 'script-defer',
          includeAssets: ['favicon.ico', 'icon-192.png', 'icon-512.png', 'fonts/*'],
          manifest: {
            name: 'pdfedt',
            short_name: 'pdfedt',
            description: 'PDF をどこにも送らずに、ブラウザの中だけで注釈を付けて保存します。',
            lang: 'ja',
            theme_color: '#1a73e8',
            background_color: '#ffffff',
            display: 'standalone',
            icons: [
              { src: 'icon-192.png', sizes: '192x192', type: 'image/png' },
              { src: 'icon-512.png', sizes: '512x512', type: 'image/png' },
            ],
          },
          workbox: {
            globPatterns: ['**/*.{js,css,html,wasm,ttf,png}'],
            // Extra typefaces (mincho, brush, etc., 30 MB in total) are not precached; they are fetched and kept when first used
            globIgnores: ['fonts/!(BIZUDPGothic)*.ttf'],
            maximumFileSizeToCacheInBytes: 12 * 1024 * 1024,
            runtimeCaching: [
              {
                urlPattern: ({ url }) => url.pathname.startsWith('/fonts/'),
                handler: 'CacheFirst',
                options: { cacheName: 'fonts', expiration: { maxEntries: 10 } },
              },
            ],
          },
        }),
    ],
    server: { headers: { 'Content-Security-Policy': csp(devScriptSrc), ...isolationHeaders } },
    preview: { headers: { 'Content-Security-Policy': csp(strictScriptSrc), ...isolationHeaders } },
  };
});
