import { test, expect, chromium, type BrowserContext, type Worker } from '@playwright/test';
import { createServer, type Server } from 'node:http';
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import type { AddressInfo } from 'node:net';
import { sample } from './helpers';

/**
 * Chrome extension (dist-ext/, generated by `pnpm build:ext`).
 * A PDF opened in the browser is redirected to the pdfedt viewer page and its content is shown.
 * Extensions load only in a persistent context, so the default page fixture is not used.
 * Unpacked extensions have "Allow access to file URLs" on by default, so the file:// path is covered here too.
 */
const extDir = resolve(process.cwd(), 'dist-ext');
test.skip(!existsSync(resolve(extDir, 'manifest.json')), 'dist-ext/ が無い（pnpm build:ext を先に実行）');

let server: Server;
let origin: string;
let context: BrowserContext;
let worker: Worker;
let extensionId: string;
/** Paths of the requests the server received */
const hits: string[] = [];

test.beforeAll(async () => {
  // Serve both a URL ending in .pdf and one identifiable as PDF only by Content-Type
  const pdf = readFileSync(sample('sample-ja-form.pdf'));
  server = createServer((req, res) => {
    const path = new URL(req.url ?? '/', 'http://x').pathname;
    hits.push(path);
    if (path === '/doc.pdf' || path === '/download') {
      res.writeHead(200, { 'content-type': 'application/pdf', 'content-length': pdf.byteLength });
      res.end(pdf);
    } else if (path === '/page.html' || path === '/fake.pdf') {
      res.writeHead(200, { 'content-type': 'text/html' });
      res.end('<title>not a pdf</title>');
    } else {
      res.writeHead(404).end();
    }
  });
  await new Promise<void>((r) => server.listen(0, '127.0.0.1', r));
  origin = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;

  context = await chromium.launchPersistentContext('', {
    channel: 'chromium',
    args: [`--disable-extensions-except=${extDir}`, `--load-extension=${extDir}`],
  });
  worker = context.serviceWorkers()[0] ?? (await context.waitForEvent('serviceworker'));
  extensionId = new URL(worker.url()).host;
  // Wait until onInstalled registers the dynamic rule
  await expect
    .poll(() => worker.evaluate(() => chrome.declarativeNetRequest.getDynamicRules().then((r) => r.length)))
    .toBe(1);
});
test.afterAll(async () => {
  await context?.close();
  await new Promise<void>((r) => server?.close(() => r()));
});

const viewer = (src: string) => `chrome-extension://${extensionId}/index.html#src=${src}`;

test('.pdf で終わる URL は要求の時点でビューワに転送され、内容が表示される', async () => {
  const page = await context.newPage();
  hits.length = 0;
  await page.goto(`${origin}/doc.pdf`);
  expect(page.url()).toBe(viewer(`${origin}/doc.pdf`));
  await page.waitForSelector('.page img');
  await expect(page.locator('.doc-name')).toHaveText('doc.pdf');
  // Once opened, #src= is removed (so a reload does not refetch over the work in progress)
  await expect.poll(() => page.url()).toBe(`chrome-extension://${extensionId}/index.html`);
  // Redirected at request time, so the server sees only the one fetch from the viewer (no load for the built-in viewer)
  expect(hits.filter((p) => p === '/doc.pdf')).toHaveLength(1);
  await page.close();
});

test('Content-Type が PDF の URL はヘッダー受信後にビューワへ差し替わる', async () => {
  const page = await context.newPage();
  // The swap may abort the original navigation, so ignore goto failures and wait for the URL to change
  await page.goto(`${origin}/download?id=1`).catch(() => {});
  await page.waitForURL(viewer(`${origin}/download?id=1`));
  await page.waitForSelector('.page img');
  await expect(page.locator('.doc-name')).toHaveText('download.pdf');
  await page.close();
});

test('file:// のローカル PDF もビューワへ差し替わる（未パッケージの拡張はファイル URL へのアクセスが既定で許可）', async () => {
  const page = await context.newPage();
  const url = pathToFileURL(sample('sample-ja-form.pdf')).href;
  // The swap aborts the original navigation (ERR_ABORTED), so ignore goto failures and wait for the URL to change
  await page.goto(url).catch(() => {});
  await page.waitForSelector('.page img');
  await expect(page.locator('.doc-name')).toHaveText('sample-ja-form.pdf');
  expect(page.url()).toBe(`chrome-extension://${extensionId}/index.html`);
  await page.close();
});

test('PDF でないページは触らない', async () => {
  const page = await context.newPage();
  await page.goto(`${origin}/page.html`);
  await expect(page).toHaveTitle('not a pdf');
  expect(page.url()).toBe(`${origin}/page.html`);
  await page.close();
});

test('.pdf で終わるが中身が PDF でない URL は、転送後にエラーを表示して開かない', async () => {
  const page = await context.newPage();
  await page.goto(`${origin}/fake.pdf`);
  expect(page.url()).toBe(viewer(`${origin}/fake.pdf`));
  await expect(page.locator('.status-bar')).toContainText('PDFではありません');
  await expect(page.locator('.page img')).toHaveCount(0);
  await page.close();
});

test('他のサイトからビューワを iframe で埋め込むことはできない（拡張の権限で任意の URL を読ませない）', async () => {
  const page = await context.newPage();
  await page.goto(`${origin}/page.html`);
  hits.length = 0;
  // Even if the extension ID is known, frame-ancestors rejects the embedding itself
  await page.evaluate(
    (src) =>
      new Promise<void>((done) => {
        const f = document.createElement('iframe');
        f.onload = () => done();
        f.src = src;
        document.body.append(f);
      }),
    viewer(`${origin}/doc.pdf`),
  );
  // The rejected iframe becomes an error page (if allowed, the viewer would fetch doc.pdf after onload)
  const frame = page.frames().find((f) => f !== page.mainFrame());
  expect(frame?.url()).toMatch(/^chrome-error:/);
  expect(hits).not.toContain('/doc.pdf');
  await page.close();
});
