import type { WrappedPdfiumModule } from '@embedpdf/pdfium';
import { wasmUtils } from '../wasm-utils';

/** Constants from fpdf_annot.h / fpdf_edit.h */
const FPDF_ANNOT_FREETEXT = 3;
const FPDF_ANNOT_STAMP = 13;
const FPDF_ANNOT_FLAG_PRINT = 1 << 2;
const FPDF_FONT_TRUETYPE = 2;

export type TextAnnotSubtype = 'freetext' | 'stamp';

export interface TextAnnotSpec {
  /** Bottom-left origin, pt (page coordinates) */
  rect: { left: number; bottom: number; right: number; top: number };
  text: string;
  fontSize: number;
  /** 0–255 */
  color?: { r: number; g: number; b: number };
  /** Subset TrueType font (must contain every character of this annotation) */
  fontData: Uint8Array;
  padding?: number;
  subtype: TextAnnotSubtype;
}

/**
 * Adds a Japanese text annotation together with an appearance stream (/AP) with an embedded font.
 *
 * - 'stamp'   : the FPDFAnnot_AppendObject path. Uses only upstream PDFium's public API,
 *               and the font lands correctly in /AP's /Resources. Displays in every viewer.
 *               Acrobat treats it as a "stamp"; it cannot be re-edited as text.
 * - 'freetext': the EPDFAnnot_SetAppearanceFromPage path. Acrobat treats it as a text annotation, but
 *               @embedpdf/pdfium 2.15.1 has a bug where the outer /AP content is wrong
 *               (fixed on runtime main on 2026-09-17), so the text disappears in Poppler/MuPDF.
 *               'stamp' stays the default until the next release.
 *
 * Neither calls GenerateContent on the page itself (original unchanged, P2).
 */
export function addJapaneseTextAnnot(
  m: WrappedPdfiumModule,
  docPtr: number,
  pagePtr: number,
  spec: TextAnnotSpec,
): boolean {
  const u = wasmUtils(m);
  const { rect, text, fontSize, fontData } = spec;
  const color = spec.color ?? { r: 0, g: 0, b: 0 };
  const padding = spec.padding ?? 2;
  const lines = text.split(/\r?\n/);
  const lineHeight = fontSize * 1.2;

  // EPDFPage_CreateAnnot creates the annotation dictionary as an indirect object
  // (FPDFPage_CreateAnnot makes a direct object, which MuPDF-based viewers cannot read)
  const annot = m.EPDFPage_CreateAnnot(pagePtr, spec.subtype === 'stamp' ? FPDF_ANNOT_STAMP : FPDF_ANNOT_FREETEXT);
  if (!annot) return false;
  try {
    if (!u.withRectF(rect, (p) => m.FPDFAnnot_SetRect(annot, p))) return false;
    m.FPDFAnnot_SetFlags(annot, FPDF_ANNOT_FLAG_PRINT);
    // /Contents: for text extraction, accessibility and re-editing in other tools
    u.withWide(text, (p) => m.FPDFAnnot_SetStringValue(annot, 'Contents', p));

    if (spec.subtype === 'stamp') {
      // /AP is generated by AppendObject. Coordinates are page coordinates (BBox = /Rect)
      const font = u.withBytes(fontData, (p, n) => m.FPDFText_LoadFont(docPtr, p, n, FPDF_FONT_TRUETYPE, true));
      if (!font) return false;
      try {
        for (const [i, line] of lines.entries()) {
          const obj = m.FPDFPageObj_CreateTextObj(docPtr, font, fontSize);
          u.withWide(line, (p) => m.FPDFText_SetText(obj, p));
          m.FPDFPageObj_SetFillColor(obj, color.r, color.g, color.b, 255);
          const baseline = rect.top - padding - fontSize - i * lineHeight;
          m.FPDFPageObj_Transform(obj, 1, 0, 0, 1, rect.left + padding, baseline);
          if (!m.FPDFAnnot_AppendObject(annot, obj)) return false;
        }
      } finally {
        m.FPDFFont_Close(font);
      }
      return true;
    }

    // --- freetext: draw the appearance as a page of a temporary document and import it into the annotation ---
    u.withWide(`0 g /Helv ${fontSize} Tf`, (p) => m.FPDFAnnot_SetStringValue(annot, 'DA', p));
    const width = rect.right - rect.left;
    const height = rect.top - rect.bottom;
    const tmpDoc = m.FPDF_CreateNewDocument();
    if (!tmpDoc) return false;
    try {
      const tmpPage = m.FPDFPage_New(tmpDoc, 0, width, height);
      const font = u.withBytes(fontData, (p, n) => m.FPDFText_LoadFont(tmpDoc, p, n, FPDF_FONT_TRUETYPE, true));
      if (!font) return false;
      try {
        for (const [i, line] of lines.entries()) {
          const obj = m.FPDFPageObj_CreateTextObj(tmpDoc, font, fontSize);
          u.withWide(line, (p) => m.FPDFText_SetText(obj, p));
          m.FPDFPageObj_SetFillColor(obj, color.r, color.g, color.b, 255);
          m.FPDFPageObj_Transform(obj, 1, 0, 0, 1, padding, height - padding - fontSize - i * lineHeight);
          m.FPDFPage_InsertObject(tmpPage, obj);
        }
        if (!m.FPDFPage_GenerateContent(tmpPage)) return false;
        if (!m.EPDFAnnot_SetAppearanceFromPage(annot, tmpDoc, 0)) return false;
      } finally {
        m.FPDFFont_Close(font);
        m.FPDF_ClosePage(tmpPage);
      }
    } finally {
      m.FPDF_CloseDocument(tmpDoc);
    }
    return true;
  } finally {
    m.FPDFPage_CloseAnnot(annot);
  }
}
